### ISSUE TITLE
Switch to the 4th version of the API

### ISSUE THREAD

**Issue by mzgol** [scottgonzalez/node-browserstack#32]
BrowserStack has now the 4th version of the API; the only difference is that v3 was http whereas v4 is https.

**Comment by scottgonzalez** [comment]
Thanks for filing this issue :-)

v4 support is now available in v1.2.0. I didn't bump the major version because nothing actually changes for the end user, even though the default version is now v4.

Wiki is updated to include v3 docs as well.
