### ISSUE TITLE
Switch to 4.0 API

### ISSUE THREAD

**Issue by jzaefferer** [scottgonzalez/node-browserstack#34]
BrowserStack released 4.0, moving everything to HTTPS, while deprecating all previous versions of the API: https://www.browserstack.com/javascript-testing-api#documentation

As far as I can tell, nothing else changed, so the switch from 3.0 to 4.0 should be pretty straight forward.

**Comment by scottgonzalez** [comment]
v4 has been the default API version used by node-browserstack since July ;-)
