### ISSUE TITLE
Automate API and code linter

### ISSUE THREAD

**Issue by kartsims** [scottgonzalez/node-browserstack#35]
Hi @scottgonzalez !

I am back with a new soon-to-be PR to support Automate API. BrowserStack actually proposes 3 APIs... And I also need the last one for my project so I thought I would implement its [features](https://www.browserstack.com/automate/rest-api) to your NPM module too...

It is pretty simple so I will just propose the PR following best practices that we did last time for Screenshots API...

One thing though where we had some troubles was code style. I use Atom with the jsbeautify plugin, which can get code style configuration from a .jsbeautifyrc file so I thought it would be nice to include it in the repo, what do you think ? To do so, I would need your file in whatever format it is. Could you provide me that in a Gist or something ?

Thanks !

**Comment by scottgonzalez** [comment]
> I am back with a new soon-to-be PR to support Automate API.

Wonderful :-)

> It is pretty simple so I will just propose the PR following best practices that we did last time for Screenshots API...

Sounds good. Based on the last PR, I'm not worried about doing any upfront discussions on API design.

> One thing though where we had some troubles was code style. I use Atom with the jsbeautify plugin

It seems like this might be specific to the editor, not to the underlying beautifiers. Do you know if this will delegate to other config files like `.jscsrc` or if the underlying JS beautifier that it uses can be installed standalone for use outside of Atom?

**Comment by kartsims** [comment]
Editor plugin is [atom-beautify](https://github.com/Glavin001/atom-beautify), most certainly based on [js-beautify](https://github.com/beautify-web/js-beautify) even though I couldn't find a reference from the 1st project to the 2nd, they use the same `.jsbeautifyrc` file format.

After diving deeper into this, we might be good enough with a linter as it seems JSCS does the fixing too sometimes. Anyway there also happens to be a [linter for JSCS](https://atom.io/packages/linter-jscs) in Atom so a `.jscsrc` file would be enough for me to prevent code style issues. Would you put it in a Gist ? This way I would test it against my fork

**Comment by scottgonzalez** [comment]
I just pushed a commit that changes the formatting to a style I prefer (as opposed to following the jQuery style). Here's the gist for the JSCS settings that match the new style: https://gist.github.com/scottgonzalez/c6f9631086af2819d941

**Comment by scottgonzalez** [comment]
Once you've confirmed this will work for you, I'm also going to add npm run scripts for linting and fixing style issues.
