### ISSUE TITLE
Implement AutomateClient#updateSession()

### ISSUE THREAD

**Issue by scottgonzalez** [scottgonzalez/node-browserstack#41]
See https://github.com/scottgonzalez/node-browserstack/pull/36#issuecomment-194999038

**Comment by kartsims** [comment]
I am running some tests and `reason` doesn't seem to get updated when provided in the `/sessions/<session-id>.json` endpoint. Any input on this @shirish87 ?

I have tried strings with and without spaces, and in all caps, just in case... Maybe the documentation should be updated about this ? If I can file an issue somewhere else please let me know

**Comment by kartsims** [comment]
As mentioned, the `reason` parameter is not working so it won't be included in the implementation nor the README

I also implemented a `deleteSession` method as the API provides an endpoint for this.

I saw a PR ongoing for CI ans Travis implementation, I would be interested in implementing the tests for the Automate API when the PR will pass through so I will be watching this.

**Comment by kartsims** [comment]
Regarding @shirish87's [comment](https://github.com/scottgonzalez/node-browserstack/pull/43#issuecomment-203634108), this issue could be done now.
