### ISSUE TITLE
Readme update to show createWorker new url navigation

### ISSUE THREAD

**Issue by gitnickgit** [scottgonzalez/node-browserstack#44]
Ok so here is whats happening, and this could be that I'm trying to do something wrong 

from BrowserStack.createClient  I create a client.createWorker from one of the browsers with an appended url.  It works great and I get see the results, but I cant figure out how to access the client.createWorker id so I can then implement a client.changeUrl   I'm new to callbacks so I haven't fully grocked it but I do have one working.  ok here is some sample code of what I'm doing:

```
function main(callback) {
    var testables = {};
    client.getBrowsers(function( error, browsers) {
        if(error) {
            return callback(error);
        }
        //OS Groups
        os_groups = _.groupBy(browsers, 'os');
        windows = _.groupBy(os_groups.Windows, 'os_version');
        osx = _.groupBy(os_groups['OS X'], 'os_version');
        ios = _.groupBy(os_groups['ios'], 'os_version');
        android = _.groupBy(os_groups['android'], 'os_version');


        //windows 10
        windows_10 = _.groupBy(windows['10'], 'browser');
        testables.windows_10_chrome = _.max(windows_10.chrome, function(ten_chrome){return ten_chrome.browser_version;});
        testables.windows_10_firefox = _.max(windows_10.firefox, function(ten_firefox){return ten_firefox.browser_version;});
        testables.windows_10_ie = _.max(windows_10.ie, function(ten_ie){return ten_ie.browser_version;});
        //osx El Capitan
        osx_ElCap = _.groupBy(osx['El Capitan'], 'browser');
        testables.osx_ElCap_chrome = _.max(osx_ElCap.chrome, function(El_chrome){return El_chrome.browser_version;});
        testables.osx_ElCap_firefox = _.max(osx_ElCap.firefox, function(El_firefox){return El_firefox.browser_version;});
        testables.osx_ElCap_safari = _.max(osx_ElCap.safari, function(El_safari){return El_safari.browser_version;});
        callback(null, testables);
    });
}

function handleMainResult(err, result) {
    if (err) {
        console.error(err.stack || err.message);
        return;
    }
    console.log("RESULT", result);
    for(var testpoint in result){
        console.log("TESTPOINT", testpoint);
        var testpointproperties = result[testpoint];
        testpointproperties["project"] = testpoint;
        testpointproperties["url"] = siteurl;
        testpointproperties["timeout"] = 5;
        //console.log(testpointproperties);
        client.createWorker(testpointproperties);
    };

    urlList = getUrls();
    console.log(urlList);
};
```

Context:
The end result is that I want to be able to build my projects based on OS and browser
then download the screenshots to integrate the results into a jenkins job that will populate an internal website with latest screen shots.

**Comment by gitnickgit** [comment]
also I know my formatting on the node side is all wrong.  I'll clean it up and make it adhere to standards after I get first working iteration done.

**Comment by shirish87** [comment]
Hey @gitnickgit, let me know if this helps. Please do reach out to support@browserstack.com if you need any assistance. It would be interesting to hear about your use-case.

````
client.createWorker(testpointproperties, function (err, worker) {
  if (err) {
    // handle error
    console.log(err);
    return;
  }

  client.changeUrl(worker.id, {
    url: 'http://example.com'
  }, function (err, data) {
    // handle err, if any
    // or process data
  });
});
````

**Comment by scottgonzalez** [comment]
As @shirish87 has shown, `createWorker()` is asynchronous and you must provide a callback if you want to do anything with the worker later.

I'm going to close this issue since there's no actual bug for me to work on (the README won't host complex sample code and all the information needed for the individual parts is already there). However, feel free to continue posting comments if you need more help and we'll continue to respond.
