### ISSUE TITLE
Getting: "Uncaught TypeError: Invalid Version: "

### ISSUE THREAD

**Issue by LarryEitel** [scottgonzalez/node-browserstack#48]
I get the following when it tries to `const BrowserStack = require('browserstack')`
or ES6
`import BrowserStack from 'browserstack'`

ideas please 

```
Uncaught TypeError: Invalid Version: 
    at new SemVer (eval at <anonymous> (app.js:8368), <anonymous>:293:11)
    at compare (eval at <anonymous> (app.js:8368), <anonymous>:570:10)
    at Function.lt (eval at <anonymous> (app.js:8368), <anonymous>:604:10)
    at Object.eval (eval at <anonymous> (app.js:8374), <anonymous>:10:12)
    at eval (eval at <anonymous> (app.js:8374), <anonymous>:56:30)
    at Object.<anonymous> (app.js:8374)
    at __webpack_require__ (app.js:556)
    at fn (app.js:87)
    at Object.eval (eval at <anonymous> (app.js:8362), <anonymous>:6:1)
    at eval (eval at <anonymous> (app.js:8362), <anonymous>:103:30)
```

**Comment by scottgonzalez** [comment]
Sorry, no ideas and I don't plan on tracking down problems with webpack. If you or someone else tracks down the problem and sends a PR, I will review it.

**Comment by kartsims** [comment]
What version of `node-browserstack` have you specified in `package.json` ?

Can you please also state your versions of NPM and NodeJS ?

**Comment by kartsims** [comment]
This issue seems to relate to this one https://github.com/npm/npm/issues/7506

Something to do with the webpack version you are using maybe ? Suggested solutions from this other issue :

- use webpack version installed locally, not globally

- run `npm update` (?..)

Can you please try these solutions ?

As stated by @scottgonzalez it seems to be a webpack issue, not related to `node-browserstack`...

**Comment by LarryEitel** [comment]
@kartsims thank you for the suggestions. I installed webpack locally and run npm update.  Unfortunately, I still get same error.

**Comment by kartsims** [comment]
> What version of `node-browserstack` have you specified in `package.json` ?

> Can you please also state your versions of NPM and NodeJS ?

How are you using the local install of webpack ? To use the local version, you should either execute it in an NPM script or via a `.js` file. Please send some code samples if you want help with this

**Comment by LarryEitel** [comment]
`"browserstack": "^1.5.0",`

**Comment by LarryEitel** [comment]
FYI, I am basing my use of this repo on [CoPilot](https://github.com/misterGF/CoPilot).

**Comment by kartsims** [comment]
Please provide a full example to reproduce the issue

**Comment by LarryEitel** [comment]
@kartsims I can appreciate your request however, I don't know when I will have to time to do this. If/when I do, I will reopen this issue. Thank You.
