### ISSUE TITLE
Feature request: Add support for the App Automate API

### ISSUE THREAD

**Issue by decates** [scottgonzalez/node-browserstack#55]
It looks very similar to the automate API, but uses a different base URL. 

Docs:
[Automate API](https://www.browserstack.com/app-automate/rest-api)
[App Automate API](https://www.browserstack.com/app-automate/rest-api)

**Comment by scottgonzalez** [comment]
I'm not a mobile app developer, so I don't have anything to test with. I'm happy to review a PR though.

**Comment by satyasreem** [comment]
App Automate API was added recently. (See the closed PRs). Requesting this to be published .

**Comment by scottgonzalez** [comment]
Just published v1.6.0.
