### ISSUE TITLE
Feature request : Add support to get video_url

### ISSUE THREAD

**Issue by uinest** [scottgonzalez/node-browserstack#59]
I dont know if it is possible to get video_url from the current solution. Please advise if it is. If not can you please add support to get it. 

Thanks

**Comment by kartsims** [comment]
Have you tried?

Which API endpoint are you referring to?

**Comment by scottgonzalez** [comment]
`createClient` itself does not give you the list of browsers. You have to explicitly ask for that using `getBrowsers`. `video_url` is part of a [session](https://github.com/scottgonzalez/node-browserstack#session-objects), so you'll need to actually create a session in order to get a video URL.

**Comment by kartsims** [comment]
You might also have an authentication issue, iirc the browsers list is the only route available when you are not authenticated
