### ISSUE TITLE
Response.errors property from Browserstack is a string

### ISSUE THREAD

**Issue by zeljko-bilandzija** [scottgonzalez/node-browserstack#71]
With some requests I got response.errors property from browserstack as string instead as array of errors.
Due that reason, in client.js I got an error 
`TypeError: response.errors.map is not a function on line.`

**Comment by scottgonzalez** [comment]
@shirish87 is this a bug in BrowserStack or should we update this module?

**Comment by shirish87** [comment]
Thanks Scott. I'm no longer with BrowserStack, but I've requested folks there to check :)
